version: '3.8'

services:
  db:
    image: mysql
    restart: always
    container_name: security-db
    environment:
      MYSQL_ROOT_PASSWORD: 56789
      MYSQL_DATABASE: security_db
    ports:
      - '3306:3306'